# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantlocation_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
